### ISSUE TITLE
Player heads not pasting

### ISSUE THREAD

**Issue by TangoMangoMC** [TotalFreedom/worldedit#31]
- Player Heads will not paste correctly, they are just blank skeleton skulls. 
(Via https://github.com/TotalFreedom/TotalFreedomMod/issues/2151)

**Comment by JeromSar** [comment]
The WE version you're running is not compatible with the server version. You can add an up-to-date adapter in the WE config directory to fix this. Google search for more details. :)

**Comment by ncurran02** [comment]
@JeromSar, this is for TotalFreedom.

**Comment by JeromSar** [comment]
@Focusvity It may be. I am not active on TF anymore, and as far as I know, the TFM and WE versions have diverged. You might want to bring this issue up with the corresponding developer.
