### ISSUE TITLE
Question about disabled blocks.

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/worldedit#6]
How do I make it so when OPs use certain blocks, it broadcasts and de-ops them?
Ex:
looperXD tried to lava,
lava is disabled in worldedit

**Comment by JeromSar** [comment]
@looperXD Have you tried coding it, perhaps? The feature doesn't exist yet :)

**Comment by JeromSar** [comment]
@looperXD Add the block as a forbidden-block in the config file. :)
