### ISSUE TITLE
WorldEdit Restrictions Unchanged

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/worldedit#7]
@JeromSar I Updated the disallowed blocks in my config http://pastebin.com/8RfSUg4q
and players are still able to use the blocks! Log from my telnet. http://pastebin.com/ZWhkvsBX

**Comment by JeromSar** [comment]
@looperXD Make sure that
* The players in question are not superadmin
*  You're using the TF-WorldEdit, not the main worldedit.
